# Generated by Django 4.2.2 on 2023-06-16 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z ]+$",
                                "Name can only contain letters and spaces.",
                            )
                        ],
                    ),
                ),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("contact", models.CharField(max_length=18, unique=True)),
                ("address", models.TextField(max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("P", "Patient"),
                            ("D", "Doctor"),
                            ("A", "Admin"),
                            ("R", "Receptionist"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
