# Generated by Django 4.2.2 on 2023-07-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='patient',
        ),
    ]
