# Generated by Django 4.2.2 on 2023-07-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
