# Generated by Django 4.2.2 on 2023-07-11 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0005_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Name can only contain letters and spaces.')])),
                ('l_name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Name can only contain letters and spaces.')])),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=18, unique=True)),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
