# Generated by Django 4.2.2 on 2023-07-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0006_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
