# Generated by Django 4.2.2 on 2023-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0008_alter_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
