# Generated by Django 4.2.2 on 2023-07-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0009_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(default='MBBS', max_length=50),
        ),
    ]
