# Generated by Django 4.2.2 on 2023-07-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0010_delete_appointment_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
