# Generated by Django 4.2.2 on 2023-07-23 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caredoor_app", "0012_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="availability",
        ),
        migrations.AddField(
            model_name="user",
            name="check_in",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="check_out",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 23, 21, 52, 39, 164869)
            ),
        ),
    ]
