# Generated by Django 4.2.2 on 2023-07-23 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caredoor_app", "0013_remove_user_availability_user_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 23, 21, 53, 20, 386864)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
