# Generated by Django 4.2.2 on 2023-07-23 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caredoor_app",
            "0014_alter_appointment_start_time_alter_user_check_in_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 23, 23, 56, 0, 466933)
            ),
        ),
    ]
