# Generated by Django 4.2.2 on 2023-07-24 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0018_alter_appointment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 3, 7, 34, 947752)),
        ),
    ]
