# Generated by Django 4.2.2 on 2023-08-06 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0020_alter_appointment_start_time_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('image', models.CharField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 11, 41, 46, 179033)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='delivered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 11, 41, 46, 179631)),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='caredoor_app.categories'),
        ),
    ]
