# Generated by Django 4.2.2 on 2023-08-06 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0021_categories_alter_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 11, 44, 35, 375999)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='delivered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 11, 44, 35, 376792)),
        ),
    ]
