# Generated by Django 4.2.2 on 2023-08-06 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0023_alter_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
