# Generated by Django 4.2.2 on 2023-08-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0024_alter_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='caredoor_app.categories'),
        ),
    ]
