# Generated by Django 4.2.2 on 2023-08-06 21:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0026_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, null=True, size=None),
        ),
    ]
