# Generated by Django 4.2.2 on 2023-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0027_user_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='fee',
            field=models.IntegerField(default=2000),
        ),
    ]
