# Generated by Django 4.2.2 on 2023-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0028_categories_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='fee',
            field=models.IntegerField(default=1300),
        ),
    ]
