# Generated by Django 4.2.2 on 2023-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0029_alter_categories_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('patient', models.CharField()),
                ('doctor', models.CharField()),
                ('charges', models.IntegerField()),
            ],
            options={
                'db_table': 'cashflow',
            },
        ),
    ]
