# Generated by Django 4.2.2 on 2023-09-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0030_cashflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='date',
        ),
    ]
