# Generated by Django 4.2.2 on 2023-09-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0031_rename_time_cashflow_datetime_remove_cashflow_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='datetime',
            new_name='appointment_datetime',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='doctor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='patient',
            field=models.CharField(max_length=255),
        ),
    ]
