# Generated by Django 4.2.2 on 2023-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredoor_app', '0032_rename_datetime_cashflow_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
